config/routes.rb
Rails.application.routes.draw do
  resources :drinks
  resources :vegetables
  resources :lunches
  resources :breakfasts
  resources :menus
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/vegetables_controller.rb
class VegetablesController < ApplicationController
  before_action :set_vegetable, only: [:show, :edit, :update, :destroy]

  # GET /vegetables
  # GET /vegetables.json
  def index
    @vegetables = Vegetable.all
  end

  # GET /vegetables/1
  # GET /vegetables/1.json
  def show
  end

  # GET /vegetables/new
  def new
    @vegetable = Vegetable.new
  end

  # GET /vegetables/1/edit
  def edit
  end

  # POST /vegetables
  # POST /vegetables.json
  def create
    @vegetable = Vegetable.new(vegetable_params)

    respond_to do |format|
      if @vegetable.save
        format.html { redirect_to @vegetable, notice: 'Vegetable was successfully created.' }
        format.json { render :show, status: :created, location: @vegetable }
      else
        format.html { render :new }
        format.json { render json: @vegetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vegetables/1
  # PATCH/PUT /vegetables/1.json
  def update
    respond_to do |format|
      if @vegetable.update(vegetable_params)
        format.html { redirect_to @vegetable, notice: 'Vegetable was successfully updated.' }
        format.json { render :show, status: :ok, location: @vegetable }
      else
        format.html { render :edit }
        format.json { render json: @vegetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vegetables/1
  # DELETE /vegetables/1.json
  def destroy
    @vegetable.destroy
    respond_to do |format|
      format.html { redirect_to vegetables_url, notice: 'Vegetable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vegetable
      @vegetable = Vegetable.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vegetable_params
      params.require(:vegetable).permit(:name, :price)
    end
end

app/helpers/vegetables_helper.rb
module VegetablesHelper
end

app/views/vegetables/_form.html.erb
<%= form_with(model: vegetable, local: true) do |form| %>
  <% if vegetable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vegetable.errors.count, "error") %> prohibited this vegetable from being saved:</h2>

      <ul>
        <% vegetable.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vegetables/edit.html.erb
<h1>Editing Vegetable</h1>

<%= render 'form', vegetable: @vegetable %>

<%= link_to 'Show', @vegetable %> |
<%= link_to 'Back', vegetables_path %>

app/views/vegetables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vegetables</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vegetables.each do |vegetable| %>
      <tr>
        <td><%= vegetable.name %></td>
        <td><%= vegetable.price %></td>
        <td><%= link_to 'Show', vegetable %></td>
        <td><%= link_to 'Edit', edit_vegetable_path(vegetable) %></td>
        <td><%= link_to 'Destroy', vegetable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vegetable', new_vegetable_path %>

app/views/vegetables/new.html.erb
<h1>New Vegetable</h1>

<%= render 'form', vegetable: @vegetable %>

<%= link_to 'Back', vegetables_path %>

app/views/vegetables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vegetable.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @vegetable.price %>
</p>

<%= link_to 'Edit', edit_vegetable_path(@vegetable) %> |
<%= link_to 'Back', vegetables_path %>