config/routes.rb
Rails.application.routes.draw do
  resources :drinks
  resources :vegetables
  resources :lunches
  resources :breakfasts
  resources :menus
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lunch.rb
class Lunch < ApplicationRecord
    
end

app/controllers/lunches_controller.rb
class LunchesController < ApplicationController
  before_action :set_lunch, only: [:show, :edit, :update, :destroy]

  # GET /lunches
  # GET /lunches.json
  def index
    @lunches = Lunch.all
  end

  # GET /lunches/1
  # GET /lunches/1.json
  def show
  end

  # GET /lunches/new
  def new
    @lunch = Lunch.new
  end

  # GET /lunches/1/edit
  def edit
  end

  # POST /lunches
  # POST /lunches.json
  def create
    @lunch = Lunch.new(lunch_params)

    respond_to do |format|
      if @lunch.save
        format.html { redirect_to @lunch, notice: 'Lunch was successfully created.' }
        format.json { render :show, status: :created, location: @lunch }
      else
        format.html { render :new }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lunches/1
  # PATCH/PUT /lunches/1.json
  def update
    respond_to do |format|
      if @lunch.update(lunch_params)
        format.html { redirect_to @lunch, notice: 'Lunch was successfully updated.' }
        format.json { render :show, status: :ok, location: @lunch }
      else
        format.html { render :edit }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lunches/1
  # DELETE /lunches/1.json
  def destroy
    @lunch.destroy
    respond_to do |format|
      format.html { redirect_to lunches_url, notice: 'Lunch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lunch
      @lunch = Lunch.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lunch_params
      params.require(:lunch).permit(:name, :price)
    end
end

app/helpers/lunches_helper.rb
module LunchesHelper
end

app/views/lunches/_form.html.erb
<%= form_with(model: lunch, local: true) do |form| %>
  <% if lunch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lunch.errors.count, "error") %> prohibited this lunch from being saved:</h2>

      <ul>
        <% lunch.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lunches/edit.html.erb
<h1>Editing Lunch</h1>

<%= render 'form', lunch: @lunch %>

<%= link_to 'Show', @lunch %> |
<%= link_to 'Back', lunches_path %>

app/views/lunches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lunches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lunches.each do |lunch| %>
      <tr>
        <td><%= lunch.name %></td>
        <td><%= lunch.price %></td>
        <td><%= link_to 'Show', lunch %></td>
        <td><%= link_to 'Edit', edit_lunch_path(lunch) %></td>
        <td><%= link_to 'Destroy', lunch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lunch', new_lunch_path %>

app/views/lunches/new.html.erb
<h1>New Lunch</h1>

<%= render 'form', lunch: @lunch %>

<%= link_to 'Back', lunches_path %>

app/views/lunches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lunch.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @lunch.price %>
</p>

<%= link_to 'Edit', edit_lunch_path(@lunch) %> |
<%= link_to 'Back', lunches_path %>