config/routes.rb
Rails.application.routes.draw do
  resources :drinks
  resources :vegetables
  resources :lunches
  resources :breakfasts
  resources :menus
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/breakfast.rb
class Breakfast < ApplicationRecord
    
end

app/controllers/breakfasts_controller.rb
class BreakfastsController < ApplicationController
  before_action :set_breakfast, only: [:show, :edit, :update, :destroy]

  # GET /breakfasts
  # GET /breakfasts.json
  def index
    @breakfasts = Breakfast.all
  end

  # GET /breakfasts/1
  # GET /breakfasts/1.json
  def show
  end

  # GET /breakfasts/new
  def new
    @breakfast = Breakfast.new
  end

  # GET /breakfasts/1/edit
  def edit
  end

  # POST /breakfasts
  # POST /breakfasts.json
  def create
    @breakfast = Breakfast.new(breakfast_params)

    respond_to do |format|
      if @breakfast.save
        format.html { redirect_to @breakfast, notice: 'Breakfast was successfully created.' }
        format.json { render :show, status: :created, location: @breakfast }
      else
        format.html { render :new }
        format.json { render json: @breakfast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breakfasts/1
  # PATCH/PUT /breakfasts/1.json
  def update
    respond_to do |format|
      if @breakfast.update(breakfast_params)
        format.html { redirect_to @breakfast, notice: 'Breakfast was successfully updated.' }
        format.json { render :show, status: :ok, location: @breakfast }
      else
        format.html { render :edit }
        format.json { render json: @breakfast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breakfasts/1
  # DELETE /breakfasts/1.json
  def destroy
    @breakfast.destroy
    respond_to do |format|
      format.html { redirect_to breakfasts_url, notice: 'Breakfast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breakfast
      @breakfast = Breakfast.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def breakfast_params
      params.require(:breakfast).permit(:name, :price)
    end
end

app/helpers/breakfasts_helper.rb
module BreakfastsHelper
end

app/views/breakfasts/_form.html.erb
<%= form_with(model: breakfast, local: true) do |form| %>
  <% if breakfast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(breakfast.errors.count, "error") %> prohibited this breakfast from being saved:</h2>

      <ul>
        <% breakfast.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/breakfasts/edit.html.erb
<h1>Editing Breakfast</h1>

<%= render 'form', breakfast: @breakfast %>

<%= link_to 'Show', @breakfast %> |
<%= link_to 'Back', breakfasts_path %>

app/views/breakfasts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Breakfasts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breakfasts.each do |breakfast| %>
      <tr>
        <td><%= breakfast.name %></td>
        <td><%= breakfast.price %></td>
        <td><%= link_to 'Show', breakfast %></td>
        <td><%= link_to 'Edit', edit_breakfast_path(breakfast) %></td>
        <td><%= link_to 'Destroy', breakfast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Breakfast', new_breakfast_path %>

app/views/breakfasts/new.html.erb
<h1>New Breakfast</h1>

<%= render 'form', breakfast: @breakfast %>

<%= link_to 'Back', breakfasts_path %>

app/views/breakfasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @breakfast.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @breakfast.price %>
</p>

<%= link_to 'Edit', edit_breakfast_path(@breakfast) %> |
<%= link_to 'Back', breakfasts_path %>